<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Create the protocol_attachments table.
     */
    public function up(): void
    {
        Schema::create('protocol_attachments', function (Blueprint $table) {
            $table->id();

            // The protocol to which this file belongs.
            $table->foreignId('protocol_id')
                ->constrained()
                ->cascadeOnDelete();

            // The filename displayed to the user.
            $table->string('original_name');

            // The private storage path generated by Laravel.
            $table->string('file_path');

            // Examples: application/pdf, image/jpeg.
            $table->string('mime_type')->nullable();

            // File size in bytes.
            $table->unsignedBigInteger('file_size');

            // The user who uploaded the attachment.
            $table->foreignId('uploaded_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->timestamps();
        });
    }

    /**
     * Remove the protocol_attachments table.
     */
    public function down(): void
    {
        Schema::dropIfExists('protocol_attachments');
    }
};